<a href="https://colab.research.google.com/github/Kumaraman6723/AIML/blob/main/PythonCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np



In [7]:
a = np.array([1,2,3,4])
a

b= np.array([5,6,7,8])

c=np.array([9,10,11,12])

d=a+b+c
d.sort()
print(d)


[15 18 21 24]


In [15]:
e=d= np.array([(7,3,1),(14,15,36)],dtype=float)
e
g=np.zeros((3,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
s=d*e
s

array([[4.900e+01, 9.000e+00, 1.000e+00],
       [1.960e+02, 2.250e+02, 1.296e+03]])

In [17]:
i=np.arange(10,25,5)
i

array([10, 15, 20])

In [20]:
j=np.linspace(0,2,9)
j

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
k=np.full((2,2),7)
k

array([[7, 7],
       [7, 7]])

In [24]:
i=np.eye(2)
i

array([[1., 0.],
       [0., 1.]])

In [26]:
n=np.random.random((2,2))
n

array([[0.74393888, 0.38013163],
       [0.56106392, 0.92972305]])